### ISSUE TITLE
Atualizar README do projeto

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#1]
Atualmente o texto é o mesmo do template. Atualizar para conter informações relevantes. O README do repositório https://github.com/grintex/app-covid é uma ótima fonte a ser copiada sem dó.

**Comment by CleissonVieira** [comment]
Realizei pull request das alterações no readme no branch dev. Acredito que o merge para o master fica a cargo do responsável pelo repositório.
