### ISSUE TITLE
Card para horário de ônibus no aplicativo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#101]
A ideia é mostrar um valor mais atual (maior em tamanho de texto no card) e, com alguma seta ou semelhante, mostrar mais algumas informações do futuro (por exemplo, os 5 proximos horários de onibus).

**Comment by GuilhermeGraeff** [comment]
Acho que essa era a ideia inicial do card, com os dados estáticos, ainda podem ser feitas muitas alterações para estilizar e etc.

![image](https://user-images.githubusercontent.com/48657331/120373262-84be4880-c2ee-11eb-830a-06df7e87a91b.png)

**Comment by GuilhermeGraeff** [comment]
Eu percebi apenas depois que o card deveria estar na aba env.f7.html, daí, me espelhando no pull request do Alisson ficou assim:
![app](https://user-images.githubusercontent.com/48657331/120377805-fcdb3d00-c2f3-11eb-8964-50138987a81e.gif)

**Comment by GuilhermeGraeff** [comment]
Puts, eu dei PR com umas bordas nos horários e origem/destino, pra ver como estavam funcionando a disposição das divs, o que eu devo fazer em seguida para resolver este problema?

**Comment by Dovyski** [comment]
Se o PR não foi aceito (ou revisado ainda), tu pode fazer alterações nele (novos commits na branch `101` do teu fork, por exemplo). O PR será atualizado automaticamente.

**Comment by CleissonVieira** [comment]
Revisado e tudo ok.
