### ISSUE TITLE
Card para responder uma enquete

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#102]
Criar um card que tenha algumas opções (botões, links, etc) para responder alguma enquete/pergunta. O card deve mostrar a pergunta em questão e as opções para escolha.

**Comment by stefanimeneghetti** [comment]
Quando fui realizar a tarefa percebi que na tela já existe um card com opções para responder uma enquete/pergunta, portanto não sei exatamente como prosseguir com ela.

![Captura de tela de 2021-06-02 09-02-27](https://user-images.githubusercontent.com/51202548/120476966-93a20b00-c381-11eb-99a7-c6020313527c.png)

**Comment by Dovyski** [comment]
Pode criar uma outra card onde cada uma das opções que o usuário escolher é um botão (algo em torno de 3 opções), por exemplo. Essa card seria uma variação da que existe hoje, só que com todas as opções disponíveis a um clique (e não ter que selecionar o valor e, depois, clicar em confirmar).

**Comment by stefanimeneghetti** [comment]
O card foi criado no arquivo `src/pages/env.f7.html` os dados fictícios para gerar o card foram criados no arquivo `src/static/example-data/environment.json`.

![Captura de tela de 2021-06-03 20-24-20](https://user-images.githubusercontent.com/51202548/120725201-cf38f400-c4ab-11eb-8491-74d7ebae02d4.png)

**Comment by CleissonVieira** [comment]
PR revisado e demonstrado a implementação em reunião conforme imagens acima.
Ficou muito bom!
