### ISSUE TITLE
Card para listagem do calendário acadêmico (timeline)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#112]
Um card na tela de contexto para mostrar todas as datas do calendário acadêmico, em estilo de timeline. Alguns dias "ao redor" da data atual são mais proeminentes, o resto estará listado com menos destaque na lista.

Os dados de data devem vir de um json com `data_inicio`, `data_fim` e `titulo`.

**Comment by GuilhermeGraeff** [comment]
Eu estou com o card pronto aqui, como eu fiz por fork (posteriormente acho que também vamos fazer por issues no repositório do App assim como no Mural), vou aguardar o Cleisson dar merge no Pull Request do Alisson que está arrumando os conflitos para poder dar fetch na minha branch -> pull na minha local e assim fazer o Pull Request com as atualizações do Alisson.
