### ISSUE TITLE
Mostrar notificações nativas no android utilizando algum plugin do cordova

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#113]
Mostrar algum aviso utilizando o próprio sistema do Android para isso (ícone na barrinha do topo).

Esse [repositório](https://github.com/Dovyski/scifibot) provavelmente já tenha alguma coisa usando isso.

Termos para verificar: push notification e plugin cordova notification

**Comment by stefanimeneghetti** [comment]
Notificação adicionada:

![Captura de tela de 2021-06-18 17-31-29](https://user-images.githubusercontent.com/51202548/122613399-29fd4e80-d05b-11eb-9552-83d8a239d10e.png)

![Captura de tela de 2021-06-18 17-32-58](https://user-images.githubusercontent.com/51202548/122613446-3ed9e200-d05b-11eb-802e-162eaecb8ec2.png)

Foi utilizado o plugin [cordova-plugin-local-notification](https://www.npmjs.com/package/cordova-plugin-local-notification) para gerar a notificação. O botão para acionar a notificação foi adicionado no arquivo `src/pages/notifications.f7.html` e é necessário ativar a variável notificationsPage no arquivo `src/js/isenabled.js` para acessa-lo. Além disso, também é necessário instalar o aplicativo no celular para testar a funcionalidade.
**OBS:** mantive o ícone do aplicativo do covid pois ao ajustar os outros pontos que também estão utilizando este ícone este ponto já será corrigido

**Comment by CleissonVieira** [comment]
Revisado, atualizado repositório 113 com a Dev e merge aceito.
