### ISSUE TITLE
Tutorial para gerar apk e abrir no celular

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/app-practice#116]
Objetivo dessa issue é criar um tutorial de como gerar o apk e rodar no dispositivo móvel.

@stefanimeneghetti comentou em reunião que encontrou uma maneira mais "practica" para gerar o apk. 
Por esse motivo foi a ganhadora da tarefa desse tutorial.

O tutorial deve ser feito no README do repositório ´app-practice´. Dessa forma fica público para todos acessarem.
Em caso de gravar vídeo com dicas da para  criar uma pasta [nesse local](https://drive.google.com/drive/u/3/folders/1AxDA7xDbmomoA_i_SIUn_UYksbfZYuvf) do drive e informar no README com uma pequena descrição.

**Comment by stefanimeneghetti** [comment]
Tutorial criado no PR #128. Como comentei na reunião voltei atrás com relação ao que estava fazendo e deixei ele super enxuto e apenas citando o que é necessário instalar e configurar para gerar o apk já que o unico processo que seria igual em vários sistemas operacionais seria a instalação do Android Studio (que por sua vez é muito simples) e dessa forma seria inviável fazer um tutorial completo ensinando a instalar e configuarar tudo passo a passo.
