### ISSUE TITLE
Ajustar nome de quem comentou o serviço

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#118]
Os nomes estão sendo trocados em comparação com o site do mural e app:

![image](https://user-images.githubusercontent.com/51202705/122406474-42844080-cf57-11eb-827c-a1ef05120229.png)

![image](https://user-images.githubusercontent.com/51202705/122406581-562fa700-cf57-11eb-82d5-9751a78b6090.png)

Aparentemente o app considera que o usuário é dono de todos os serviços e, por isso, o primeiro comentário (que é a descrição do serviço) fica com o nome do usuário que está acessando

**Comment by alissonpeloso** [comment]
Os nomes estão sendo trocados em comparação com o site do mural e app:

![image](https://user-images.githubusercontent.com/51202705/122406474-42844080-cf57-11eb-827c-a1ef05120229.png)

![image](https://user-images.githubusercontent.com/51202705/122406581-562fa700-cf57-11eb-82d5-9751a78b6090.png)

Aparentemente o app considera que o usuário é dono de todos os serviços e, por isso, o primeiro comentário (que é a descrição do serviço) fica com o nome do usuário que está acessando

**Comment by alissonpeloso** [comment]
> _No description provided._

**Comment by stefanimeneghetti** [comment]
Esse bug foi corrigido com o PR #142 com a adição de um filtro para exibir apenas os serviços solicitados pelo usuário do app, sendo assim os nomes agora são exibidos corretamente.
