### ISSUE TITLE
Busca periódica de informações do mural e disparo de notificação em caso de mudança

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#123]
Focar no campo `updated_at` das solicitações. Buscar na API uma lista de pedidos e, baseado no valor do campo `updated_at` do que está no servidor e do que tem localmente, criar uma notificação.

Na tela de configurações, colocar algum forma de ligar/deligar essa sincronização. O tempo pode ser definido por uma config interna.

**Comment by stefanimeneghetti** [comment]
Como comentei  na reunião de hoje ao iniciar a tarefa percebi que, ao que parece, os dados das solicitações não estão sendo armazenados no dispositivo mesmo com a opção ativada nas configurações. Então como os dados serem armazenados é necessário para ser possível disparar a notificação vou verificar isso com mais calma e caso o armazenamento realmente não esteja sendo feito vou corrigir essa parte para dar continuidade a tarefa.

**Comment by stefanimeneghetti** [comment]
Como discutido em reunião as notificações serão feitas por meio do Firebase Cloud Message e ficaram a cargo da issue #135
