### ISSUE TITLE
Erro ao executar o app

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#13]
Vários da equipe estão enfrentando um erro ao tentar executar o app em seus ambientes locais de desenvolvimento. O erro que eu estou enfrentando é o que está logo abaixo:

![erro](https://user-images.githubusercontent.com/18292676/88428226-db9feb00-cdca-11ea-889a-4e3b5f048a49.png)

Se alguém estiver enfrentando outro erro, favor comentar aqui. Esse problema é bem urgente porque impede o desenvolvimento de várias outras tarefas.

**Comment by Dovyski** [comment]
Qual versão do `node` do `npm` voces estao usando?

**Comment by arufonsekun** [comment]
Está faltando um diretório chamado build que deveria estar no projeto, me desculpem :disappointed:
