### ISSUE TITLE
Salvar dados do app no dispositivo para usar offline

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/app-practice#131]
Ao logar no aplicativo é requisitado dados da API para utilizar no mesmo:

**Objetivo:** salvar os dados da requisição na memória do dispositivo, dessa forma é possível utilizar offline

**Comment by stefanimeneghetti** [comment]
Funcionalidade implementada no PR #141. Agora quando a tela de listagem de serviços é acessada os dados são salvos no dispositivo para que seja possível acessar a página mesmo com o dispositivo offline, os dados da pagina de detalhes do serviço (como descrição mais detalhada e comentários) são também salvos quando essa página é acessada. É possível apagar os dados salvos pela página de configuração do dispositivo bem como ativar e desativar a opção de salvar os dados (caso o dispositivo possua informações salvas ao desativar esta opção as mesmas são apagadas).

**OBS**: A implementação dessa funcionalidade acabou piorando um pouco os impactos do bug relatado na issue  #119 já que mesmo sem acesso a API alguns dados serão carregados, mas como já havia uma issue para este problema acabei não focando na solução disso.
