### ISSUE TITLE
UX / UI em telas ativas para lançamento

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/app-practice#134]
Precisamos dar um carinho nessas telas do Aplicativo para lançar. Indiquei algumas telas onde precisam ser acariciadas e citei exemplos, porém sita-se livre para dar seu toque:

Login: 

- [x] Colocar botão para ver senha, dessa forma o usuário pode verificar se digitou correto

QR Code:

- [x] Após ler um QR a info é gerada abaixo, porém não da para fazer interações. **Objetivo:** realizar uma interação após clicar na infos gerada, seja para abrir no app ou abrir no navegador se for uma URL.

Contexto:

- [x] Inserir um [LottiFiles](https://lottiefiles.com/) no inicio com uma mensagem logo abaixo informando que nessa tela são funcionalidades que estão em desenvolvimento. Que é apenas uma demonstração ao público. 

Aura:

- [x] Limpar conversas e deixar como padrão para quando um usuário acessa pela primeira vez a tela da aura ela trás a seguinte mensagem: 
`Olá <nome do usuário>. Espero lhe encontrar bem! Meu nome é Aura e estou aqui para lhe ajudar. Me encontro em fase de desenvolvimento, para lhe demonstrar minha utiliza digite as seguintes palavras: acc.
`  
Da para acrescentar todas as palavras onde são gatilhos para funcionalidades / fluxos / brincadeiras da mesma para o usuário receber uma demonstração.

- [x] Qualquer outro conjunto de caracteres que não tenha um contexto para o bot deve ser respondida pela Aura com uma mensagem padrão: `Desculpa, ainda estou em desenvolvimento, logo terei mais funcionalidades para lhe ajudar.`

Noticias:

- [x] Entender o porque quando acessada a tela de notícia (newsPage) está ocorrendo um erro e as noticias não retornam.
O request é feito na url do [feed.xml](https://practice.uffs.cc/feed.xml)

Serviços: 

- [x] Na tela de serviços existem duas categorias: Serviços solicitados e Serviços concluídos. Porém existem várias categorias que precisam ser acrescentadas. **Objetivo:** manter / criar os serviços "Aguardando aprovação", "Em progresso", "Concluídos" e "Recusados". Da para utilizar o componente Nested List, onde substitui o nome pela categoria, e após clicar no nome os itens expandidos dentro seriam as listagens das solicitações nessa categoria, porém precisa limitar a quantidade de itens expandidos e inserir uma paginação para ver os demais. Ou então encontrar outro modo.
![image](https://user-images.githubusercontent.com/29258164/126053315-e21f2f62-c5f5-4854-8e4a-5b5c0960a3e6.png)

**Comment by alissonpeloso** [comment]
> Precisamos dar um carinho nessas telas do Aplicativo para lançar. Indiquei algumas telas onde precisam ser acariciadas e citei exemplos, porém sita-se livre para dar seu toque:
> 
> Login:
> 
> * [x]  Colocar botão para ver senha, dessa forma o usuário pode verificar se digitou correto
> 
> QR Code:
> 
> * [x]  Após ler um QR a info é gerada abaixo, porém não da para fazer interações. **Objetivo:** realizar uma interação após clicar na infos gerada, seja para abrir no app ou abrir no navegador se for uma URL.
> 
> Contexto:
> 
> * [x]  Inserir um [LottiFiles](https://lottiefiles.com/) no inicio com uma mensagem logo abaixo informando que nessa tela são funcionalidades que estão em desenvolvimento. Que é apenas uma demonstração ao público.
> 
> Aura:
> 
> * [x]  Limpar conversas e deixar como padrão para quando um usuário acessa pela primeira vez a tela da aura ela trás a seguinte mensagem:
>   `Olá <nome do usuário>. Espero lhe encontrar bem! Meu nome é Aura e estou aqui para lhe ajudar. Me encontro em fase de desenvolvimento, para lhe demonstrar minha utiliza digite as seguintes palavras: acc. `
>   Da para acrescentar todas as palavras onde são gatilhos para funcionalidades / fluxos / brincadeiras da mesma para o usuário receber uma demonstração.
> * [x]  Qualquer outro conjunto de caracteres que não tenha um contexto para o bot deve ser respondida pela Aura com uma mensagem padrão: `Desculpa, ainda estou em desenvolvimento, logo terei mais funcionalidades para lhe ajudar.`
> 
> Noticias:
> 
> * [x]  Entender o porque quando acessada a tela de notícia (newsPage) está ocorrendo um erro e as noticias não retornam.
>   O request é feito na url do [feed.xml](https://practice.uffs.cc/feed.xml)
> 
> Serviços:
> 
> * [ ]  Na tela de serviços existem duas categorias: Serviços solicitados e Serviços concluídos. Porém existem várias categorias que precisam ser acrescentadas. **Objetivo:** manter / criar os serviços "Aguardando aprovação", "Em progresso", "Concluídos" e "Recusados". Da para utilizar o componente Nested List, onde substitui o nome pela categoria, e após clicar no nome os itens expandidos dentro seriam as listagens das solicitações nessa categoria, porém precisa limitar a quantidade de itens expandidos e inserir uma paginação para ver os demais. Ou então encontrar outro modo.
>   ![image](https://user-images.githubusercontent.com/29258164/126053315-e21f2f62-c5f5-4854-8e4a-5b5c0960a3e6.png)

Ele só não carrega as notíficas pois está no localhost e não há permissão de fazer request do feed.xml, mas no apk, isso funciona normal. 
![image](https://user-images.githubusercontent.com/51202705/127008693-600e2db1-d1d1-47f2-83bc-41055acbb078.png)

**Comment by CleissonVieira** [comment]
Perfeitooo, ficou muito bom @alissonpeloso 

Apenas essa linha de status "Aguardando aprovação          Em progresso" foi conversado para modificar e deixar mais intuitivo, pois existem mais status se arrastar para o lado, porém usuários leigos terão dificuldades de entender isso.

Assim que alterado essa tarefa será finalizada

![image](https://user-images.githubusercontent.com/29258164/127564050-a2a19d2e-fe49-4fa7-b9be-2ed06f1ea17e.png)

**Comment by CleissonVieira** [comment]
Topsster agora sim hehehe 

![image](https://user-images.githubusercontent.com/29258164/128115056-65319ccf-a683-4dec-9429-8db09031655c.png)
