### ISSUE TITLE
Processar notificação push vinda do FCM

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#136]
Depois que o FCM for integrado no aplicativo, tratar notificações push vindas do FCM. No momento, o app precisa se preocupar apenas com um tipo de mensagem (que indica que existem atualizações em alguma solicitação no mural).

No futuro, o aplicativo receberá notificações push e, a partir da análise dos dados dessa notificação, realizará uma ação (ex. mostrar uma tela em especifico). Como não temos isso agora, qualquer push que chegar pode ser tratado como "Tem coisa nova no mural".

**Comment by CleissonVieira** [comment]
Informado na última reunião que issue não é mais relevante.
