### ISSUE TITLE
Ajustar sheet da solicitação de serviço

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#152]
A gavetinha que abre ao solicitar novo serviço acaba cobrindo alguns campos quando abre o teclado do smartphone, ajustar para que apareça, talvez com uma barra de rolagem.

![image](https://user-images.githubusercontent.com/51202705/129635502-cd60dbb7-e555-45f3-aa9b-18cdaf7ab50b.png)

**Comment by CleissonVieira** [comment]
Criado um modal, isso resolveu a situação, já disponível na dev
