### ISSUE TITLE
Adicionar delivery_date na demonstração dos serviços

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#153]
adicionar o delivery date no app ao listar os serviços

**Comment by CleissonVieira** [comment]
@alissonpeloso por gentileza, inclui nessa mesma tarefa também:

- [ ] Retirar a escrita "Logo" na parte superior da página da assistente virtual.
![image](https://user-images.githubusercontent.com/29258164/129790699-bb914ba9-4522-4db0-8cc7-9cae3bc9004a.png)

**Comment by CleissonVieira** [comment]
@alissonpeloso  estou fechando essa tarefa, pois foi conversado via telegram.
Alisson informou que desenvolveu a tarefa, eu verifiquei e testei, logo identifiquei dois itens para concluir essa primeira versão, então criei a issue #154 e nela será feito PR e merge das alterações desta tarefa também.
