### ISSUE TITLE
Lançar aplicativo V1 na google play

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/app-practice#159]
Acessar o [console da Google Play](https://play.google.com/console/u/0/developers) com a conta de Gmail abaixo e inserir a branch master com a versão 1 do aplicativo para lançamento.

Gmail: practiceuffs@gmail.com
A senha pode encontrar [nesse arquivo](https://docs.google.com/document/d/1ZTdpl25dCmZ-E6QWiivqmHvp6XytJhI44II9AAoYVug/edit).

**Comment by alissonpeloso** [comment]
Os problemas com a versão do cordova foram resolvidos. Só preciso da renovação da key para upar na google play.

arquivo .aab: `cordova/platforms/android/app/release/app-release.aab`

**Comment by Dovyski** [comment]
A renovação da chave depende do Google?

**Comment by alissonpeloso** [comment]
> A renovação da chave depende do Google?

Siim, eu tive que gerar um certificado da nova key e mandar por e-mail, aí eles vão renovar em algum momento

**Comment by alissonpeloso** [comment]
![image](https://user-images.githubusercontent.com/51202705/132261952-f172382d-e6a1-4ef5-a5e9-04a9ea76ecc6.png)

Eles responderam o e-mail, quarta-feira vai estar liberado pra fazer um upload com a chave que solicitei atualizar.

**Comment by alissonpeloso** [comment]
Mais um problema, hehe.

![image](https://user-images.githubusercontent.com/51202705/132673989-7bf9caf2-0bea-4864-8abb-65b52cdca520.png)

Aparentemente, precisa adicionar um link de política e privacidade pois o app utiliza da permissão da camêra:

![image](https://user-images.githubusercontent.com/51202705/132674111-36222a99-275b-4a9f-a23a-bfd8ab3ee7a6.png)

**Comment by Dovyski** [comment]
Pode colocar esse link como política de privacidade:

https://practice.uffs.edu.br/privacidade

Ele ainda não está funcional, mas podemos colocar ele no ar sem problemas.

@practice-uffs/dev criar essa url em nosso site e colocar o seguinte
conteúdo nela (usar só o texto, o layout fica o do nosso site do practice):

https://grintex.uffs.cc/privacy/app-covid/

**Comment by alissonpeloso** [comment]
Boa, obrigado!

**Comment by alissonpeloso** [comment]
App em análise:

![image](https://user-images.githubusercontent.com/51202705/132843683-657e0d9a-5f13-4e8b-b216-d97218cd680a.png)

**Comment by alissonpeloso** [comment]
Link do App: [https://play.google.com/store/apps/details?id=cc.uffs.practice](https://play.google.com/store/apps/details?id=cc.uffs.practice)
