### ISSUE TITLE
Tela de solicitação de serviços: ordem de apresentação dos serviços 

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/app-practice#161]
A tela de solicitação de servições está listando os serviços pelas áreas sem considerar o volume de demandas que recebemos.

Minha sugestão é criar uma "categoria" chamada principais serviços (ou outro nome) e colocar os serviços mais utilizados. Na apresentação da tela esta categoria aparece primeiro na tela.

Cada equipe pode eleger os serviços que devem aparecer nesta categoria.

Obs: mesma situação no Mural

**Comment by CleissonVieira** [comment]
@alissonpeloso da para pegar a tag que transforma os serviços em populares no Mural V2 e criar a nova categoria.
No caso está em refatoração essa parte, então logo informo quando concluída para implementar no aplicativo.
