### ISSUE TITLE
Erro ao carregar comentários e informações da solicitação

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#186]
Ao clicar em algum serviço criado pelo `mural`, ele não consegue carregar as mensagens e dá um alert com a mensagem que ocorreu um erro inesperado.

PrintScreen
![photo_2021-11-18_09-09-40](https://user-images.githubusercontent.com/51202705/142413464-82ababb9-c583-4459-9c78-7affea755426.jpg)

**Comment by stefanimeneghetti** [comment]
Eu verifiquei e aparentemente o problema é com a rota da api acessada por essa página então criei [uma issue](https://github.com/practice-uffs/api/issues/19) no repositório da API para resolver isso.

**Comment by CleissonVieira** [comment]
> Eu verifiquei e aparentemente o problema é com a rota da api acessada por essa página então criei [uma issue](https://github.com/practice-uffs/api/issues/19) no repositório da API para resolver isso.

A issue criada pela @stefanimeneghetti foi concluída, @Dovyski  informou no comentários o commit.
