### ISSUE TITLE
Verificar se é possível usar o `iframe` da aura criada na API e vincular diretamente no app

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#215]
Foi criado um widget na `API` com a aura como um iframe, onde poderíamos integrar a aura com qualquer aplicação do Practice. 

A ideia é verificar se é possível integrar a aura (no formato criado na API) diretamente com o aplicativo de forma simples. Assim, poderíamos trabalhar com alterações na aura diretamente na API e sempre que fosse alterado ou alguma função nova fosse implementada não seria necessário ajustar nada nos aplicativos.

Se for possível, implementar e após abrir tarefa para incluir isso nos demais aplicativos feitos com `Framework7`.

**Comment by GuilhermeGraeff** [comment]
Por enquanto testei apenas na web, assim que possível eu tento gerar o apk, porém tenho que estudar ainda para ver como acessar a api local a partir da minha rede...

Acho que seria algo neste sentido né?

![image](https://user-images.githubusercontent.com/48657331/159283734-7406539d-3687-4716-b69a-2f9f5e0c15d3.png)

**Comment by alissonpeloso** [comment]
Siim, como comentei contigo, podemos mudar o layout também, pra ficar melhor. Tipo um botão flutuante que abre uma página com o chat ou algo assim. Importante ver do teclado no mobile.

**Comment by GuilhermeGraeff** [comment]
Enquanto vou evoluindo vou colocando aqui, eu pensava que não encaixaria tão bem quanto encaixou, por serem coisas diferentes, mas agora me parece até bem aplicável.

Estou fazendo os testes na Dev do App-practice com a Dev da API, não criei branch nem nada, vou aguardar a reunião de amanhã (23/03) para decidirmos algo.

Já aproveito o comentário pra tirar uma dúvida, na minha implementação eu utilizo o JWT passado pelo link de source do i-frame para autenticar o usuário, eu já teria este JWT caso autenticado no app também né? (como se estivesse autenticado no mural por exemplo)

Notar que, ainda é necessário fazer a implementação da autorização para coleta de dados no chat da api.

<hr />

![image](https://user-images.githubusercontent.com/48657331/159471551-e8add8e5-0899-493a-a6bc-e3b7fa5259bf.png)

![image](https://user-images.githubusercontent.com/48657331/159471820-e2ce1fc5-4590-4888-b29c-5f61fc5772a0.png)

**Comment by alissonpeloso** [comment]
Sim, se tu pegar no storage vai ter o token do usuário, dá pra verificar se tem o token e já autenticar pra não precisar usar o login de novo na interface da aura. Tá bem daora, mas acho que vamos ter que adaptar o layout pra aura usando aquele botão que eu falei, acho que fica mais bonito, mas a gente vê na reunião de amanhã.

**Comment by alissonpeloso** [comment]
@GuilhermeGraeff, tú conseguiu gerar o apk para testar o app?

**Comment by GuilhermeGraeff** [comment]
Opa, acabei deixando passar o comentário, acabei focando um pouco no maker e com isso não consegui gerar o APK ainda, eu tentei começar o ambiente do zero em uma máquina virtual, mas acabei tomando o mesmo erro que tomava linux mint de antes... erro esse que eu não estava conseguindo corrigir.

Enquanto estava escrevendo isso eu corrigi o erro e gerei o apk, agora vou tentar colocar o iframe com a aura para funcionar :) ashuuahuhsa, vou deixar aqui anotado pq pode ajudar alguém algum dia

<hr />
Estava tomando esse erro:

![image](https://user-images.githubusercontent.com/48657331/161959543-04a7f60d-fc96-43e7-9cf4-85d3af59522f.png)

Resolvi marcando os seguintes selects:

![image](https://user-images.githubusercontent.com/48657331/161963343-c2b63b42-7ec2-46de-ae6e-636e2936a7aa.png)

**Comment by GuilhermeGraeff** [comment]
<hr />

Consegui gerar um [APK](https://drive.google.com/file/d/1KzOguIpokGr8ggvTIlKnEkGeMf0ry499/view?usp=sharing) para poder prosseguir, então da minha parte agora acho que já foi verificado que é possível utilizar o widget, agora temos que ver com a equipe se isso realmente deve ser implementado, vou marcar o Líder @alissonpeloso já que ele está responsável pelo app-practice.

Se for acertado de utilizar o Widget, então eu abro uma branch aqui e implemento o chat.

Notem que, se não houver conexão com internet não é possível conectar na aura e fica uma tela de 'Página Web não disponível', algo que eu não consegui passar por cima ainda...

Também, por ter que conectar à uma página Web, notar que pode demorar até aparecer o chat....

![image](https://user-images.githubusercontent.com/48657331/162807890-646b0c73-3065-43c4-abd4-c8b1e0da9527.png)

<hr />

**Comment by GuilhermeGraeff** [comment]
O scrum master aprovou, prosseguimos na #219 !

![image](https://user-images.githubusercontent.com/48657331/162973122-ad015794-4094-4f68-9976-2906b7385d80.png)
