### ISSUE TITLE
Criar tela tela Inicial

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#22]
Criar a tela inicial conforme a estrutura abaixo.

Tela: [H001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_213)

![Descrição aplicativo - app-practice](https://user-images.githubusercontent.com/512405/89334301-addd6080-d66c-11ea-9488-38afa294ac05.png)

Elementos que simbolizam texto (retangulos cinza) podem ser trocardos por textos lorem ipsum.

**Comment by andrewmsilva** [comment]
Pelo que eu entendi da tela inicial e das outras que ela concede acesso, seriam Tabs que levariam para as outras telas pelos seus respectivos ícones (tipo no app do Facebook). Estou implementando isso e, se é isso mesmo, então deveria haver mais um ícone: um pra tela inicial. Sem um ícone para a Home, o fluxo para essas telas me parece um pouco confuso, porque se a Tab só tem as 4 opções, não dá pra voltar pra Home através dela. 

Fiz um GIF do que fiz até agora para que possam visualizar melhor:

![home-tab-app-practice](https://user-images.githubusercontent.com/18292676/89452979-e8123500-d734-11ea-95cd-64552ff62c72.gif)

Percebam que o identificador de cada tela está presente no GIF, assim podem consultar no documento de engenharia se necessário. Se estiverem de acordo, eu faço a Tab com essas 5 abas. Se não, posso alterar sem problemas, contanto que me elucidem melhor esse fluxo, assim reduzimos um possível retrabalho para ajustar o fluxo posteriormente.

Obs: o GIF é apenas para contextualizar sobre as Tabs e as telas. Quaisquer outros elementos e componentes do layout devem ser ignorados.

**Comment by Dovyski** [comment]
É isso mesmo e eu concordo, Andrew. Pode adicionar um ícone para a Home.

**Comment by andrewmsilva** [comment]
Estrutura criada com alguns exemplos de dados. Segue um GIF para facilitar a visualização:

![inicial-app-practice](https://user-images.githubusercontent.com/18292676/89595958-656ca100-d82c-11ea-9e48-dae0c380700f.gif)
