### ISSUE TITLE
Testar React e Flutter

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/app-practice#227]
A ideia dessa issue é testar o funcionamento do `widget da aura` e o medidor de batimentos cardíacos (app bem-estar).

- [x] Flutter
- [x] React

**Comment by alissonpeloso** [comment]
Flutter: https://pub.dev/packages/heart_bpm

**Comment by SWE3T** [comment]
Vou ir deixando algumas notas: 
 - Para **instalar** o React Native, foram apenas duas linhas no NPM e já foi, super rápido e intuitivo; Pode ser que seja por eu já ter tudo instalado certinho (Android Studio e Dispositivos virtuais) pois no próprio site diz que quem vai instalar tudo do 0, leva cerca de uma hora para conseguir; 
 - Notei também que ele tem aquele sistema de módulos (ou Widgets) bem forte; assim como o Flutter;

Já encontrei erros mas os que eu achei foram muito fáceis de serem corrigidos por ter uma comunidade mais ativa e grande que o do Framework7; E um detalhe que eu achei muito legal foi a possibilidade de gerar a build do aplicativo pela rede WIFI, sem precisar de cabos (agrega bastante pra experiência de desenvolver).

Estou no processo de colocar um iFrame com o chat da aura pra ver no que vai dar; Vou ir contanto as atualizações conforme forem surgindo; 

Coloquei um iFrame e tenho que dizer que foi muito promissor; O widget WebView, responsável por mostrar as páginas se comporta como o navegador padrão do meu celular; muito fluído. **Nota:** Vale a pena testar em celulares mais fracos, eu tenho apenas o meu para testar mas pode ser que caso o celular possua pouca memória RAM, ele venha a engasgar;

**Comment by alissonpeloso** [comment]
Eu testei o widget da aura também, e ele abriu no navegador externo quando clicava num link (que é o mais importante). Só precisaria testar em um apk pra ver se funciona, pois só testei rodando no expo

**Comment by alissonpeloso** [comment]
Gerei um apk, e ele abre os links externalmente também 🥇
