### ISSUE TITLE
Criar barra de navegação do aplicativo 

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#23]
Criar a barra de navegação que fica na base do aplicativo, visível em todas as telas:. Haverá quarto opções na barra de navegação. Usar `Tabbar` no Framework7 com labels sendo ícones do fontawesome para implementar essa issue.

![image](https://user-images.githubusercontent.com/512405/89334599-2ba16c00-d66d-11ea-97bc-16a7e08cb2b8.png)

As páginas que cada uma das opções abre está documentada [aqui](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.p).

**Comment by andrewmsilva** [comment]
Quanto aos ícones, creio que utilizaremos os nativos do Framework7 (https://framework7.io/icons/). Embora a variedade de ícones seja bem grande, o Framework7 não tem alguns dos ícones definidos no protótipo. Então eu tomei a liberdade de montar um conjunto de ícones iniciais pra poder colocar nas abas:

![opcao-1](https://user-images.githubusercontent.com/18292676/89466422-34b43b00-d74a-11ea-82af-b681d8635dea.png)

É possível perceber que eles seguem um padrão visual (todos são fechados, sem preenchimento, com linhas finas e simples). Creio que manter um padrão visual seja algo bem importante.

Existem algumas outras opções que se adequam às telas e podem substituir os ícones que estão ali. Então peço que, se quiserem que eu troque alguns dos ícones, comentem aqui com algumas sugestões dessa lista abaixo. Se tiverem sugestões que não estão nela, comentei mesmo assim, a lista é só pra facilitar a consulta de algumas possibilidades.

## Env:
![env](https://user-images.githubusercontent.com/18292676/89471193-e4da7180-d753-11ea-9ab4-c759435529d3.png)

## Scan:
![scan](https://user-images.githubusercontent.com/18292676/89471216-f0c63380-d753-11ea-8ffd-6e2982f3ddcd.png)

## Chats:
![chats](https://user-images.githubusercontent.com/18292676/89470217-a3e15d80-d751-11ea-8d5a-e733bd421f1e.png)

## News:
![news](https://user-images.githubusercontent.com/18292676/89471225-f7ed4180-d753-11ea-8bcf-43149352b8ca.png)
