### ISSUE TITLE
Implementar menu lateral (gaveta)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#24]
Gaveta de opções gerais do aplicativo fica do lado direito. Ela é aberta quando o usuário clica no ícone das “três barrinhas”, no canto superior direito.

Tela de referência: [MENU001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g86c280fb7b_0_228)

![Descrição aplicativo - app-practice (1)](https://user-images.githubusercontent.com/512405/89334826-8935b880-d66d-11ea-84f7-67d31c94d0bb.png)

**Comment by CleissonVieira** [comment]
Deixei a gaveta um pouco maior pelo falo de nome de usuário ser maior que o do exemplo. Testei com o meu. "Cleisson V. Raimundi" foi sem quebra de linha, porém se colocar "Cleisson Vieira Raimundi" então existe uma quebra de linha, pois não há como permitir ser muito extenso. 

Não consegui sobrepor a navbar (menu inferior) em cima do meu lateral (gaveta), também não consegui fazer com que a tela em baixo do menu lateral fosse empurada para o lado conforme imagem da Issue. 

Atualmente a tela ficou dessa maneira: 

![image](https://user-images.githubusercontent.com/29258164/89581346-33981200-d80d-11ea-8be4-7464244c9ca7.png)

Tenho uma sugestão que é deixar o item "Sobre" no final do menu-lateral.

**Comment by Dovyski** [comment]
Está muito bom!

> Não consegui sobrepor a navbar (menu inferior) em cima do meu lateral (gaveta), também não consegui fazer com que a tela em baixo do menu lateral fosse empurada para o lado conforme imagem da Issue.

Não tem problema. Esses detalhes podemos seguir conforme o Framework7 indicar. Se a navbar deles fica assim, eu acho melhor (inclusive aparecer sobre os ícones da navbar na base é bem melhor em termos de UX/UI).

**Comment by andrewmsilva** [comment]
Fiz algumas alterações menores no design e nos componentes e o @CleissonVieira tinha usado e inicializei as rotas para as telas que o RightPanel leva (Ideias, Serviços, etc). Para melhor visualização, vide GIF abaixo:

![right-panel-app-practice](https://user-images.githubusercontent.com/18292676/89598274-c8f9cd00-d832-11ea-8338-2cfcf136997a.gif)

Vou fechar a issue por ora, mas sintam-se a vontade para dar sugestões, opiniões e abrí-la se necessário.
