### ISSUE TITLE
Criar estrutura inicial da tela "Ambiente"

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#25]
A tela ambiente mostrará informações e interações que o usuário tem dependendo do ambiente onde ele está. Por exemplo, se o usuário estiver em uma sala XXX do campus Chapecó, uma opção que aparecerá nessa tela é “Reservar a sala XXX para o seu uso?”.

Essa tela sempre mostrará uma informação seguida de pequenos botões para interação. Por exemplo, responder/postar enquete.

O objetivo dessa tarefa não é implementar todas as funcionalidades, mas a estrutura inicial: uma área para o usuário intergir, um campo de texto com botão na base da tela para enviar dados.

Tela: [E001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_319)

![Descrição aplicativo - app-practice (2)](https://user-images.githubusercontent.com/512405/89335049-ddd93380-d66d-11ea-885e-066be7cb799a.png)

**Comment by CleissonVieira** [comment]
@andrewmsilva e @Dovyski 
Vou pedir uma análise de vocês sobre essa tela, pois fiquei confuso, não consegui compreender bem o que vai onde, ou o que exatamente tem nessa tela
Então fiz o layout de acordo com o protótipo, para quando colocar os itens apenas algumas questões precisem ser alteradas

![image](https://user-images.githubusercontent.com/29258164/89809620-2bdcb400-db12-11ea-9ac3-a9566132996a.png)

Vamos conversando e ajeitando?

**Comment by Dovyski** [comment]
Por enquanto essa tela não tem muita estrutura definida, @CleissonVieira . O melhor exemplo que eu posso te dar é a tela do Google Assistant no Android:

![image](https://user-images.githubusercontent.com/512405/89817788-19b54280-db1f-11ea-9b02-3da5656882c3.png)

A tela "Ambiente" será algo nesse sentido. Informações relevantes para o local/horário/atividade que o usuário estiver fazendo, com algum "botãozinho(s)" para interagir com isso. Para essa primeira iteração, não precisa se estressar com layout e funcionalidades.

No futuro, podemos pensar em algo mais rebuscado. Eu o [botui](https://github.com/botui/botui) e acho que podemos usar ele tanto no nosso sistema de mensagens quanto nessa tela de ambiente. Como eu falei, deixamos isso para a próxima iteração.

**Comment by andrewmsilva** [comment]
Pelo que eu entendi, esta tela será interativa com o ambiente que a pessoa se encontra. Se ele está na biblioteca, vai mostrar algumas funcionalidades que ele pode executar lá dentro, como pesquisar por livros ou reservar um notebook. Se ele entra na sala de aula, ele poderia reservar a sala se ela estiver vazia ou poderia baixar o material da aula (isso parece um pouco cyberpunk, mas seria legal).

Então a ideia é meio que mostrar as opções que existem pro ambiente que o usuário se encontra. Existem N formas de fazer isso. Daria pra mostrar o nome do ambiente que ele está (no início da página) e mostrar um card pequeno para cada funcionalidade disponível lá. Estou apenas divagando aqui 😃

**Comment by Dovyski** [comment]
Acredito que essa tarefa esteja finalizada da forma que está. Se for o caso, fechar e continuar os trabalhos na #41 .

**Comment by andrewmsilva** [comment]
Eu estava fazendo algumas alterações, mas seguirei com elas a partir da nova Issue.
