### ISSUE TITLE
Criar tela de visualização de um chat em específico

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#26]
Essa tela mostra a conversa em um grupo ou com um usuário em particular. A organização de conteúdo e interação deve ser idêntica ao do Telegram.

Para o cumprimento dessa issue, essa tela não precisa ter funcionamento real, apenas o layout com os elementos clicáveis/etc. A comunicação pode ser falsa.

Tela: [C002-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_635)

![Descrição aplicativo - app-practice (7)](https://user-images.githubusercontent.com/512405/89335752-cfd7e280-d66e-11ea-8179-0d473fe8b8db.png)

**Comment by andrewmsilva** [comment]
Eu vou pausar um pouquinho essa tarefa pra poder focar nas outras que são prioridade. Todavia, não demoro a continuá-la.

**Comment by andrewmsilva** [comment]
Estrutura inicial conluída, com template dinâmico e requisição simulada a arquivos `JSON`.

Para melhor visualização, vide GIF abaixo:
![chat-practice](https://user-images.githubusercontent.com/18292676/91894412-0869dc80-ec6c-11ea-9780-6ad868ec9e04.gif)

É evidente que são necessários vários componentes ainda não feitos, como opções de envio, responta, encaminhamento, envio de imagens, arquivos, etc. Além disso, por se tratar de um chat, as próprias requisições talvez mudem, já que é algo muito dinâmico que precisa de uma API Real Time. Mas enfim, ainda é uma versão piloto :D
