### ISSUE TITLE
Criar estrutura para tela de visualização de um serviço

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#28]
Permite a visualização de um serviço em particular. Essa tela pode ser adaptada ou compartilhada do sistema [web-feedback](https://github.com/practice-uffs/web-feedback).

Tela: [O002-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g86c280fb7b_0_424)

![Descrição aplicativo - app-practice (11)](https://user-images.githubusercontent.com/512405/89336473-d450cb00-d66f-11ea-97fd-9029835b30aa.png)

**Comment by CleissonVieira** [comment]
@Dovyski Talvez não seria melhor colocar o Título do serviço no local de "Serviço" na barra de voltar? Pois na página anterior já existe "Serviços", já é intuitivo que essa é a pagina de um serviço específico.

Então deixaria apenas o tipo e data que o serviço foi criando na linha onde tem "Tipo", "Título do serviço" e "dd/mm/aaaa hh:mm".

![image](https://user-images.githubusercontent.com/29258164/90439235-9a3deb00-e0ab-11ea-8cc1-3927cef0b9d1.png)

**Comment by Dovyski** [comment]
Hum, seria melhor sim, mas a chance do título do serviço "estourar" o tamanho disponível para a navbar é grande. Talvez trocar `Serviço` por `Visualização de serviço`, dai o resto das informações estarão no bloco abaixo, onde podemos colocar rolagem, quebrar linhas, etc.

Que tal?

**Comment by CleissonVieira** [comment]
A realmente, não tinha noção do tamanho dos títulos. Então vamos fazer dessa forma que citou.
Vou mover a data para baixo do título então, assim sobra mais espaço, e se ocorre quebra de linha já fica cada item no seu lugar.

**Comment by CleissonVieira** [comment]
Tela concluída, se encontra dessa forma: 

![image](https://user-images.githubusercontent.com/29258164/90590680-8b445f00-e1b7-11ea-9757-b33a90bfe512.png)

**Comment by andrewmsilva** [comment]
Reabrindo porque o @CleissonVieira disse que tem mais umas alterações pra commitar.

**Comment by CleissonVieira** [comment]
Melhorias finalizadas junto ao pull da tela de notícias.
