### ISSUE TITLE
Criar a estrutura da tela "Serviços"

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#4]
Essa tela é acessível através de um ícone na página home do aplicativo. Ao acessar a página serviços, o usuário é apresentado com a seguinte lista:

* Vídeo: apresentação composta (pessoa é gravada seguindo um documento de apresentação, que será intercalado via edição com as falas; baseado em https://www.youtube.com/watch?v=DoDjWzsQ4PU)
* Vídeo: apresentação simples (apenas grava a pessoa falando na câmera com o fundo que ela escolheu)
* Vídeo: animação “mão-livre” (horizonte 1)
* Audio: audio simples (uma única trilha de audio, por exemplo, fala)
* Audio: audio composto (duas ou mais trilhas de áudio, ex.: fala, música, efeitos sonoros, combinação de fontes diferentes)

**Comment by Dovyski** [comment]
Essa issue deve ser complementada (ou, se pouco foi feito, substituída) pela especificação a seguir. A tela de serviços lista os serviços que o usuário em questão solicitou ao programa. Ao clicar em um serviço, o usuário será levado a uma tela com mais informações so serviço [O002-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g86c280fb7b_0_424)

Tela: [O001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g86c280fb7b_0_342)

![Descrição aplicativo - app-practice (10)](https://user-images.githubusercontent.com/512405/89336331-9bb0f180-d66f-11ea-84f4-9c132fe997f9.png)

**Comment by CleissonVieira** [comment]
Como está no momento: 

![image](https://user-images.githubusercontent.com/29258164/90285069-85621d00-de49-11ea-9243-7840ba6e8d3e.png)
