### ISSUE TITLE
Criar estrutura de conversa na tela Ambiente (E001-A)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#41]
Tela: [E001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_319)

Vamos iniciar os trabalhos para que a tela de ambiente comece a ficar funcional. Essa tela tem o objetivo de entregar informações úteis para o contexto no qual o usuário está: se está na biblioteca, mostra informações de locações; se está em um evento, mostra quiz de perguntas do palestrante; se está em aula, mostra opções sobre como o usuário está se sentindo.

O objetivo dessa issue é integrar na tela de ambiente a interface do [botui](https://github.com/botui/botui). Depois de integrado, fazer [esse exemplo](http://examples.botui.org/thermostat-bot/) do botui funcionar na tela de ambiente do app. Se tudo der certo, o usuário abrirá a tela de ambiente no app practice e poderá interagir com esse `thermostat-bot` do exemplo.

Esse exemplo é importante porque ele tem interação "vai-e-vem" entre usuário e contexto. No futuro, teremos várias desse tipo.

**Comment by Dovyski** [comment]
Eu gosto da ideia de usar Vue no app todo, mas acho que nesse momento é uma complexidade desnecessária. Podemos integrar o Vue nessa tela de conversa como um passo inicial.

No futuro, vamos integrando em outras áreas. Que tal?

**Comment by andrewmsilva** [comment]
Bom, como eu nunca trabalhei com Vue, estou tendo dificuldade para integrar o BotUI. Então eu decidi implementar algo que usasse um conceito parecido só pra termos algo meio pronto até que eu conseguisse integrar o BotUI (ou talvez nem integre caso gostem do que eu fiz).

Eu fiz um conceito de "pins" que são mostrados de acordo com o ambiente que a pessoa está. Semelhante ao BotUI, cada pin tem um tipo, mas como fui eu quem fiz, a variedade é bem maior: `text` para textos simples, `embed` para iframes de todo tipo (vídeos do Youtube, jogos feitos por alunos, etc) e `actions` para a realização de ações, incluindo formulários customizáveis com inputs `text`, `email`, `number`, `tel`, `url`, `date`, `datetime-local` e `select`. É claro, poderiam haver mais tipos de pins (imagens, arquivos, links externos, etc), mas o que eu fiz foi só uma versão piloto para que a tela não ficasse em branco.

Eis um GIF para melhor visualização:
![env-practice](https://user-images.githubusercontent.com/18292676/91729566-2277c200-eb7b-11ea-8378-cdf3cd561e00.gif)

Gostaria de receber um feedback sobre o que eu fiz e se devo prosseguir com a integração do BotUI.

Obs: Não se sintam acanhados de preferirem o BotUI, porque o que eu fiz foi num formato pode ser facilmente adequado ao BotUI assim que ele for integrado, pois eu dei uma boa estudada na documentação dele ([clique aqui para ver o `JSON`](https://github.com/practice-uffs/app-practice/blob/dev/src/static/example-data/environment.json)).

**Comment by Dovyski** [comment]
Eu achei excelente essa tua forma de implementação, inclusive muito superior ao BotUI. Voto para seguirmos com a implementação (e flexibilidade proposta pelo) @andrewmsilva. No futuro, podemos implementar a UI do próprio BotUI dentro desse estrutura proposta.
