### ISSUE TITLE
Implementar a leitura de códigos QR usando a câmera

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#42]
Tela: [S001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_422)

Implementar a leitura real de códigos QR. Para a implementação dessa tarefa, a lib [html5-qrcode](https://github.com/mebjas/html5-qrcode) deve ser usada obrigatoriamente (a não ser que algo melhor seja encontrado; a saber: rode tanto no browser quanto em cordova; API simples; bom desempenho).

Além de ler um código QR, a aplicação precisa emitir um evento interno chamado `qr:read` (ver [esse docs](https://framework7.io/docs/events.html) sobre custom events) com a informação lida no código QR.

**Comment by CleissonVieira** [comment]
Não consegui fazer funcionar essa biblioteca, estou esquecendo de algum detalhe. Li documentação e tentei alterar a implementação. 

Instalei através do NPM e ainda tentei baixar e utilizar os arquivos puros.

Se alguém puder me dar uma luz, uma ajuda, eu agradeço demais

![image](https://user-images.githubusercontent.com/29258164/91776958-f84af200-ebc4-11ea-859e-d8465e7eecc7.png)

**Comment by Dovyski** [comment]
Tem o link para a branch onde tu está trabalhando nisso? Que dai podemos ver o código e ajudar por lá. Olhando por cima, realmente parece que o arquivo não está sendo importado corretamente.

**Comment by CleissonVieira** [comment]
Estou trabalhando [nessa branch](https://github.com/CleissonVieira/app-practice/tree/42)  do meu fork

Instalei *npm i html5-qrcode* seguindo o tutorial e importando da forma que indica, mesmo erro ocorre.
Realizei o download do arquivo colocando na pasta *js*, então importando no *header*, ou então na página *scan.f7.html* de forma que clicando na importação me direcionasse ao arquivo importado. 
Busquei tutoriais e fóruns mas também não consegui me guiar e fazer funcionar.

**Comment by Dovyski** [comment]
Olhando meio por cima, parece que falta tu colocar um `import` alguma coisa. Olha [esse código aqui](https://github.com/grintex/app-covid/blob/b15dd713e02222ab95300df2dbff9b19c6764e68/src/pages/home.f7.html#L109) que é o App covid também feito com Framework7. Tu teria que importar o `html5QrcodeScanner`.

**Comment by CleissonVieira** [comment]
Não estou mais conseguindo raciocinar hehe 
Olhei o código do covid, mas parece ser tão mais simples 

Vou dar um descanso pra cabeça pra ver se ajuda

![image](https://user-images.githubusercontent.com/29258164/92029620-328acf80-ed3c-11ea-8a82-44562a3c87e0.png)

![image](https://user-images.githubusercontent.com/29258164/92030789-ee98ca00-ed3d-11ea-860a-7056771ffa50.png)

**Comment by Dovyski** [comment]
Remove as tags 3 tags `<script>` com o `html5-qr-code.min.js` e deixa só o `import`. Deve resovler.

**Comment by CleissonVieira** [comment]
Que estranho, comentei ontem e não foi. 
Mas de inicio eu fiz sem as 3 tags, adicionei elas depois em uma nova tentativa de fazer rodar. 
Apenas o import não resolveu.

**Comment by Dovyski** [comment]
Vou baixar o teu código e dar uma olhada mais de perto. As vezes o framework7 não ajuda tanto com os erros e com libs de terceiros.

**Comment by Dovyski** [comment]
Essa issue precisa ser terminada nessa sprint (Sprint 7).

**Comment by Dovyski** [comment]
Estou trabalhando nessa issue ❤️

**Comment by CleissonVieira** [comment]
Está issue está diretamente ligada a issue #114 
Por este motivo estou fechando está tarefa e linkando na citada acima para uso de histórico.
