### ISSUE TITLE
Criar tela inicial pré-login

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#45]
Conforme acordado na issue #43, deve ser desenvolvido o conteúdo da tela inicial que o usuário acessa antes de fazer seu login. A ideia desta tela é apresentar uma mensagem de boas vindas ao usuário, dizer em poucas palavras o objetivo do app e dar possíveis instruções, assim diminui a chance de que o usuário se sinta perdido ao acessar o app pela primeira vez ou acessar depois de muito tempo sem utilizar.

No caso, a tela já existe, falta apenas inserir o conteúdo. Optei por criar esta issue para que o progresso desta tarefa fique documentado e público.

**Comment by Dovyski** [comment]
Essa tela foi além dos meus sonhos quando eu vi. Eu imaginava um textinho e um botão qualquer. Até eu que sou do programa quero usar meu iduffs para ver o que tem adiante no app 😄
