### ISSUE TITLE
Fazer com que o conteúdo das notícias seja obtido do feed.xml do site do practice

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#48]
Atualmente as notícias estão com conteúdo placeholder. Elas precisam mostrar conteúdo real agora. Para isso, as informações sobre notícias podem ser obtidas através de https://practice.uffs.cc/feed.xml . Atualmente esse feed não contém todas as informações necessárias, mas depois que https://github.com/practice-uffs/website-programa/issues/53 for implementada, isso será possível.

Vou marcar o @CleissonVieira nessa tarefa, porque ele está trabalhando na https://github.com/practice-uffs/website-programa/issues/53. Ele pode avisar quando ela ficar pronta.

**Comment by andrewmsilva** [comment]
Vou ir implementando de acordo com o arquivo disponível até o momento. Assim que for terminado, apenas farei as alterações cabíveis para a adaptação.

**Comment by andrewmsilva** [comment]
Enquanto gerava as requisições, um erro diz que https://practice.uffs.cc/feed.xml bloqueia requisições Cross-Origin:

![image](https://user-images.githubusercontent.com/18292676/92505188-18d50680-f1da-11ea-97a7-721c79478e90.png)

Isso acontece mesmo alterando o Header da requisição para aceitar essas requisições cruzadas:

```javascript
app.request({
  url: "https://practice.uffs.cc/feed.xml",
  method: "GET",
  dataType: "xml",
  crossDomain: true,
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"
  },
  success: function(res) {
    console.log(res);
  },
  error: function(xhr) {
    console.log("error");
    console.log(xhr);
  }
});
```

Pesquisando, ancontrei algumas coisas no fórum da Framework7 e as soluções sugeridas são por parte do backend, não do frontend ([link 1](https://forum.framework7.io/t/cross-origin-request-blocked/6846), [link 2](https://forum.framework7.io/t/ignoring-control-allow-origin/4216), [link 3](https://forum.framework7.io/t/cross-origin-read-blocking-corb-with-app-request/5308)). Alguma sugestão sobre o que fazer para resolver isso?

**Comment by CleissonVieira** [comment]
@andrewmsilva Feed.xml atualizado para o mesmo modelo de CC. 
A respeito do bloqueio nas requisições Cross-Origin vou ajudar a pesquisar, mas desconheço esse problema.

**Comment by Dovyski** [comment]
Isso é um problema que só pode ser resolvido no servidor que hospeda o site (`practice.uffs.cc`, no caso). Fiz as alterações necessárias no servidor. Preciso de um ok se funcionou ou não.

**Comment by andrewmsilva** [comment]
Deu certo, agora posso continuar a implementação. Grato pela agilidade 😃

**Comment by andrewmsilva** [comment]
Esta tarefa está quase pronta, mas estou enfrentando problemas com o Template7 (renderizador padrão do Framework7). Ele não está interpretando o HTML que está presente nos conteúdos das notícias que estão sendo retornadas, e meus esforços para resolver isso estão sendo frustrados.

Vejam o GIF abaixo para melhor visualização:

![news-practice](https://user-images.githubusercontent.com/18292676/92822062-20470c00-f3a2-11ea-91af-af1fa543508f.gif)

É possível notar grandes melhorias no UI e UX, mas também o problema com o HTML não interpretado. Se alguém souber de alguma possível solução, seria conveniente.

**Comment by andrewmsilva** [comment]
Agora as notícias estão sendo requisitadas do XML do site, além de terem sido feitas várias melhorias no UI e UX .

Segue um GIF para melhor visualização:
![news-practice](https://user-images.githubusercontent.com/18292676/92832959-ad905d80-f3ae-11ea-854b-9cd526beaa7c.gif)

Fico no aguardo de um feedback :D

**Comment by Dovyski** [comment]
Como diz uma amiga minha, **maravi-gold** ✨.
