### ISSUE TITLE
Vídeo de apresentação do app

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#50]
Conforme requisitado pelo @Dovyski, é necessário gravar um vídeo simples mostrando as telas e os fluxos do app.

**Comment by andrewmsilva** [comment]
Vídeo feito e disponível no [Drive](https://drive.google.com/drive/u/0/folders/1VuP72ap8EeRF8-acjw3owE4OzvE5yuhU). Preferi fazer um vídeo porque dá pra pausar e tal, ao contrário de um GIF.

**Comment by Dovyski** [comment]
Ficou maravilhoso, obrigado! ❤️
