### ISSUE TITLE
Login com idUFFS

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#51]
Atualmente, a tela de login faz uma simulação de login através do idUFFS. Precisamos que agora o login seja efetivamente feito através de uma requisição ao idUFFS. Mais informações serão adicionadas assim que possível.

**Comment by andrewmsilva** [comment]
Como eu já comino a forma que o login está implementado no app, acho que posso ficar com essa tarefa. No entanto, alguém teria algum material ou código que já faça login com idUFFS? Já temos uma API com isso? Eu devo criar uma? @Dovyski

**Comment by Dovyski** [comment]
O web-feedback já faz autenticação com o idUFFS. O melhor seria criar um endpoint na API, algo como `/api/login`, que autentique o usuário e retorne as informações que o próprio web-feedback consegue ao autenticar alguém com idUFFS.

@JeanCHilger e @arufonsekun o que vocês acham da ideia?

**Comment by JeanCHilger** [comment]
Hmm realmente seria o ideal, vamos providenciar

**Comment by Dovyski** [comment]
Vamos mudar a abordagem de login para o aplicativo. Vamos utilizar a [API do curso de Computação](https://github.com/ccuffs/api-cc).

**Comment by andrewmsilva** [comment]
Login via IdUFFS implementado com sucesso. Na verdade, a própria API de cc especifica que não é necessário token para realizar o login, então o token não foi usado para tal. No entanto, deixarei o token salvo para caso seja necessário utilizar outros endpoints de cc.

**Comment by lcaimi** [comment]
O login não está funcionando para ID que não contenham ".". Por exemplo, o meu usuário "lcaimi" obtem a mensagem de formato de ID inválido e não permite o login.

**Comment by andrewmsilva** [comment]
Por ora, o padrão para os idUFFS ficou definido como `[a-zA-Z.]+`, ou seja, qualquer sequência de caracteres que contenha letras e pontos. Caso alguém tenha algum outro padrão em mente, basta sugerir. Todadvia, o que foi feito provavelmente será suficiente para resolver os problemas apontados.
