### ISSUE TITLE
Implementar feature flags

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#52]
Para disponibilizarmos o app para o nosso usuário final, é evidente que não podemos mostrar telas e funcionalidade que não estão prontas. Portanto, faz-se necessário a implementação de `feature flags`, um sistema que habilita e desabilita determinadas funcionalidades e telas para mostrar ao usuário apenas o que realmente estiver pronto. Assim que isso estiver pronto, a ideia é que no ambiente de desenvolvimento seja possível ver tudo o que o app tem, mas que no ambiente de deploy só seja possível ver o que estiver pronto.

**Comment by Dovyski** [comment]
Para fins de referência, isso já foi implementado no [app Coronavírus Chapecó](https://github.com/grintex/app-covid) através de um js chamado [isenabled.js](https://github.com/grintex/app-covid/blob/dev/src/js/isenabled.js)

**Comment by andrewmsilva** [comment]
Adicionei feature flags para todas as telas no `IsEnabled.js` e fiz o tratamento diretamente pelas rotas, então rotas para features não disponíveis sequer são acessíveis. No entanto, é natural que existam páginas que tenham URLs que tentam acessar essas páginas, então é necessário fazer esse tratamente em todos os links que forem feitos. Portanto, apliquei isso no menu lateral e na home, pois são os componentes chave para acessar outras telas.

O resultado pode ser observado no GIF a seguir:
![feature-flags](https://user-images.githubusercontent.com/18292676/96923547-d284ef80-1487-11eb-9bd0-450a91a85180.gif)
