### ISSUE TITLE
Criar a classe Storage

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#54]
A classe `Storage` será responsável por armazenar os dados da aplicação localmente para dados possam ser persistidos. Além disso, a classe também fará comunicação com a API do web-feedback para sincronizar quaisquer elementos.

Para implementar essa issue, utilize o arquivo [abalitycs.js](https://github.com/practice-uffs/app-practice/blob/master/src/js/abalytics.js) como ponto de partida. Ele faz praticamente tudo que precisamos, porém ele faz algumas coisas a mais (como enviar estatísticas, que não é necessário na classe storage).

A classe `Storage` guardará todas as suas informações em disco como um objeto json stringficado (`JSON.stringfy`). Quando a classe for inicializada, ela deve carregar do disco essa string, parsear ela (`JSON.parse`) e colocar o objeto na memória.

A inicialização da classe `Storage` segue o [mesmo funcionamento de inicialização](https://github.com/practice-uffs/app-practice/blob/master/src/js/app.js#L69) da classe `Analytics` . Você pode utilizar essa mesma ideia.

**Comment by andrewmsilva** [comment]
O arquivo `storage.js` tem algo parecido implementado. Tem algumas funções para cuidar dos dados de autenticação e outras para lidar com as gravações de áudio. As gravações de áudio funcionam usando `JSON.stringfy` e `JSON.parse`, então podem servir de base pra fazer essa classe que centraliza o conteúdo armazenado. 

As páginas que usam essas funções são do `storage.js` são as `login.f7.html`, `record-audio.f7.html` e `right-panel.f7.html` (botão de logout). Então assim que a classe for implementada, essas páginas deve ser alteradas para usar a classe corretamente.

**Comment by andrewmsilva** [comment]
Classe criada, mas as requisições externas (como login e notícias) ainda estão em suas respectivas páginas. Vou criar issues separadas para migrar essas requisições para a classe storage.
