### ISSUE TITLE
Ajustar a página Configurações

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#55]
Depende de: #54 

Ajustar a página de configurações para que ela mostre o conteúdo descrito na tela de referência.

Referência: [T001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g86c280fb7b_0_756)

Para essa issue, não é necessário que os dados da página de configurações sejam salvos em disco.

**Comment by andrewmsilva** [comment]
Conforme definido, a tela Settings foi ajustada e três opções foram ajustadas. Os dados das opções já estão sendo armazenados dinamicamente através da classe Storage.

Segue um GIF para fácil visualização
![settings](https://user-images.githubusercontent.com/18292676/97447931-da70e380-190e-11eb-8a49-11920dcecc47.gif)
