### ISSUE TITLE
Implementar o modal MODAL001-A

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#56]
Esse modal deve ter como estrutura um elemento gráfico, um título, um texto e um botão/link de continuar. O elemento gráfico precisa ser, obrigatoriamente, um [Lottie file](https://github.com/airbnb/lottie-web). Como consequencia, a conclusão dessa tarefa envolve a integração do player web do lottie files no app.

Embora essa issue fale em modal, isso é apenas para exemplificar o comportamento desejado: algo aparecerá na tela do usuário cobrindo todo o conteúdo. Usaremos isso para mostrar mensagens de conclusão de tarefas, etc.

Eu sugiro fazer a implementação dessa tela exatamente como o `Open as modal` da [tela de login do exemplo do Framework7](https://framework7.io/docs/login-screen.html#examples). O modal de login que abre quando o usuário clica em `Open as modal` é exatamente o que queremos: um modal que cobre toda a tela e tem um botão/link para fechar.

Referência: [MODAL001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.ga39d98afe2_0_10)

**Comment by CleissonVieira** [comment]
A princípio está concluído, criei uma tela e deixei no menu especifico pra isso. Mas desativado para não ficar em produção. Isso por não saber onde é para colocar. Então quando surgir uma utilidade isso será alterado

**Comment by CleissonVieira** [comment]
Quando clica em um botão (de teste agora) abre essa tela (modal), onde esse ícone verde é um lottie, e a imagem do print é o final do "vídeo" do lottie.

![image](https://user-images.githubusercontent.com/29258164/97520130-46883180-1979-11eb-8dbc-07bb3e501c2b.png)
