### ISSUE TITLE
Atualizar membros na tela About

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#58]
Visto que houveram alterações no quadro de bolsistas e coordenadores do PRACTICE, é necessário atualizar esses dados no app também. Outra opção seria remover isso do app para evitar ter que atualizar isso. Outra opção seria uma outra tela para mostrar a equipe do app ou do PRACTICE. E mais uma opção seria carregar esses dados do site da mesma forma que é feito com as notícias (embora fosse melhor que tais dados fossem via API ou mesmo fixos). 

Aguardo sugestões (@Dovyski).

**Comment by Dovyski** [comment]
Vamos resolver isso da forma mais fácil: colocamos um link para site, na parte do histórico de participantes do programa. Dessa forma, não precisamos mais atualizar o app em ralação a isso e o site se torna o centro dessa informação.
