### ISSUE TITLE
Criar tela de login

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#6]
A tela de login deve solicitar o idUFFS e a senha do usuário. A autenticação pode ser feita utilizando-se uma das APIs do curso de Ciência da Computação (falar com @Dovyski).

**Comment by andrewmsilva** [comment]
Aparentemente, o @CleissonVieira estava criando os próprios CSSs dele para fazer os componentes ao invés de usar os que já vem nativo no Framework7. É preferível utilizar os componentes pré-prontos, mas é totalmente possível alterar alguns detalhes pra deixar os componentes mais bonitos. Favor alterar isso quando possível.

**Comment by CleissonVieira** [comment]
Obrigado pelo feedback Andrew, estou alterando.
