### ISSUE TITLE
Tela de serviços deve mostrar minhas solicitacões

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#68]
A tela de serviços do aplicativo deve mostrar uma lista com os serviços solicitados pelo usuário.

**Comment by andrewmsilva** [comment]
O layout e o design foram feitos e uma chamada teste ao endpoint foi criada. Assim que o endpoint for atualizado para utilizar o token do usuário, será possível remover a chamada teste e colocar a oficial.

Visto que num futuro próximo o app terá duas funcionalides prontas (notícias e serviços), eu achei melhor colocar os serviços como aba principal do app, pois é a funcionalidade mais importante até o momento. Esconder ela num menu lateral não seria muito conveniente no momento, mas talvez quando tivermos outras funcionalidades mais importantes.

Quanto ao layout e design, o print abaixo mostra a tela quando o usuário nunca solicitou nenhum serviço:
![practice-app-services-empty](https://user-images.githubusercontent.com/18292676/100392934-f0112000-3016-11eb-8b70-0597464514ab.png)

E o print abaixo mostra a tela quando os serviços que o usuário já solicitou:
![practice-app-services](https://user-images.githubusercontent.com/18292676/100392935-f1dae380-3016-11eb-8b8b-847a923c3e5b.png)

O "2 meses" representa há quanto tempo a solicitação foi feita. Planejo que, eventualmente, sejam colocados badges coloridos para identificar o status do serviço ou talvez agrupar os serviços em diferentes cards, cada um representando um status diferente.

**Comment by andrewmsilva** [comment]
Agora esta tela possui dois cards. O primeiro mostra os serviços ativos, ou seja, os que estão "em análise" e "em progresso". O segundo card mostra os serviços que já foram concluídos. Como o problema com os endpoints foram reolvidos, esta tela já foi testada e, considerando as especificações até o momento, está terminada.
