### ISSUE TITLE
Tela para pedido de serviço

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#69]
Na tela de serviços do aplicativo, deve existir um botão para que o usuário possa fazer uma solicitação. Ao clicar nesse botão, o usuário é apresentado com uma nova tela (ou um modal) que lista todos os serviços disponíveis. A lista de serviços disponíveis estará disponível como um endpoint do web-feedback.

Ao selecionar o serviço desejado, uma tela ou modal semelhante àquela usada no web-feedback deve ser mostrada.

**Comment by andrewmsilva** [comment]
Dando um feedback do que foi feito até agora, o layout e o design foram feitos e utilizou-se de dados de exemplo para testes. Assim que os problemas com o endpoint forem solucionados, eu ajusto a requisição.

Por ora, o layout e o design podem ser visualizados abaixo:
![app-service-options](https://user-images.githubusercontent.com/18292676/100394381-bee71e80-301b-11eb-9fb5-7b02d43a8cc6.gif)

O formulário para fazer a solicitação ainda está em desenvolvimento e será comentado aqui assim que houver uma versão.

**Comment by andrewmsilva** [comment]
Foi feito um modal para solicitar os serviços. A ideia é que o usuário não tenha que ficar procurando num `select` pela categoria e especificação que ele quer, pois assim que ele clica em solicitar, isso é carregado automaticamente. Portanto, ele apenas precisa digitar o título e a descrição.

Segue um GIF para melhor visualização:
![service-request](https://user-images.githubusercontent.com/18292676/100549788-cf81d980-3253-11eb-8852-3617dedb74bf.gif)

Todavia, o `post` feito ao endpoint está resultando num erro. Creio que ele seja no lado do servidor, e não do cliente. De qualquer forma, eis o erro:
![image](https://user-images.githubusercontent.com/18292676/100549701-54b8be80-3253-11eb-803e-b25636f460d8.png)

**Comment by andrewmsilva** [comment]
Foi adicionado um campo `select` para selecionar o campus e as chamadas aos endpoints foram ajustadas. Está funcional :D
