### ISSUE TITLE
Criar estrutura da tela de notícias

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#7]
A tela de notícias deve mostrar um feed de notícias, ao estilo do feed do instagram (imagem mais texto pequeno de informação). Nesse primeiro momento, as notícias podem ser hardcoded de um json ou array em memória.

Tela: [N001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_774)

![Descrição aplicativo - app-practice (8)](https://user-images.githubusercontent.com/512405/89335852-f5fd8280-d66e-11ea-992c-8d1151e7ee3a.png)

**Comment by CleissonVieira** [comment]
Tela para listagem de notícias:

![image](https://user-images.githubusercontent.com/29258164/90318604-0849ad00-df08-11ea-9b56-d2747a5eca7a.png)
