### ISSUE TITLE
Ideas para os cards na tela de contexto

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#70]
Acabei de ver [esse projeto](https://adaptivecards.io/) da Microsoft sobre cards para diversos aplicativos. Pelo visto, tem muita coisa que podemos usar.

**Comment by andrewmsilva** [comment]
Seria maneiro fazer isso com NLP, chat bot, TTS, etc. Seria algo bem inovador para uma universidade.

**Comment by andrewmsilva** [comment]
Todos da equipe @practice-uffs/dev podem dar ideias de cards para esta tela :heart:

**Comment by CleissonVieira** [comment]
Notei que issues com objetivos de ideias acabam sendo esquecidas pelos membros em geral, já que estão sempre em função de atividade. 
Acredito que para esses tópicos renderem ideias dos membros seria interessante fazer levantamento durante reuniões de líderes em geral, tópicos para avaliações semestrais que realizamos, mensagens fixadas em canais de conversação, também em posts nas mídias sociais verificando com a comunidade se acaso tem ideias (instagram tem uma ótima interação).
Esses tópicos funcionam enquanto estão em contato direto com o publico em geral, a galera não volta verificar issues.
