### ISSUE TITLE
Colocar requisição de notícias na classe Storage

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#72]
Embora a classe storage tenha sido implementada a fim de centralizar as requisições de dados do app, a requisição de notícias ainda está sendo feita na tela de notícias. Portanto, é necessário refatorar essa parte para que fique certinho.

**Comment by Dovyski** [comment]
Estava pensando e não sei se é uma boa ideia colocarmos as notícias no storage interno. Acho que podemos pensar nesse armazenamento como algo para guardar dados que sejam primordiais para que a aplicação funcione. O que vocês acham?

**Comment by andrewmsilva** [comment]
Concordo com isso. A ideia da issue era só colocar a requisição às notícias na classe Storage e retirar da tela de notícias, visto que este é o padrão seguido atualmente. Dessa forma, a tela precisa apenas chamar um método da classe Storage para obter as notícias, o que despolui um pouco o código. Mas as notícias não estão sendo armazenadas localmente, é só feita uma requisição e retornados os dados.

**Comment by andrewmsilva** [comment]
Os métodos relacionados às notícias foram movidas para a classe `storage`. Nada é armazenado, com exceção do que a própria Framework7 armazena em cache (arquivos, imagens, etc). Como o `.xml` carregado é um arquivo, pode ser que o Framework7 automaticamente armazene em cache, mas isso é um problema pra outra issue.
