### ISSUE TITLE
Criar estrutura inicial da tela escaner

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#8]
O objetivo dessa tarefa não é implementar todas as funcionalidades, mas a estrutura inicial: uma área para visualizar o que a câmera captura, um botão sobreposto a essa visão, e uma parte mostrando as informações do usuário (com um código QR qualquer).

Tela: [S001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_422)

![Descrição aplicativo - app-practice (4)](https://user-images.githubusercontent.com/512405/89335305-38728f80-d66e-11ea-8b37-9cb69fd33597.png)

**Comment by CleissonVieira** [comment]
Como está atualmente:

![image](https://user-images.githubusercontent.com/29258164/90258391-dd375e80-de1e-11ea-95ec-a8e8bbef5f4b.png)

**Comment by Dovyski** [comment]
Está ótimo dessa forma já. Deixamos para a próxima sprint a implementação da leitura do feed da câmera.

**Comment by Dovyski** [comment]
@andrewmsilva pode fazer o merge das atividades dessa tarefa e fechar a issue. Vou colocar a continuação dela em uma nova issue.
