### ISSUE TITLE
Alterar requisições para a API central

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#82]
Visto que o PRACTICE está evoluindo sua arquitetura para criar uma API central modular que pode "acoplar" múltiplos serviços e gerenciar suas requisições, faz-se necessário ajustar as requisições feitas para a API central. Todavia, como esta etapa ainda está em desenvolvimento, será necessário aguardar para que cada alteração seja feita.

- [ ] Ajustar autenticação de usuários
- [ ] Ajustar gerenciamento de serviços

**Comment by CleissonVieira** [comment]
Acredito que não tem proposito especifico essa tarefa. 
Quando necessário criar issues com tarefa definida para tais ajustes.
