### ISSUE TITLE
Gerenciamento do token do usuário

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/app-practice#85]
Atualmente, o token do usuário é apenas obtido ao realizar login, sendo que é necessário atualizá-lo de tempos em tempos, pois ele pode expirar se o usuário ficar inativo por muito tempo. Se isso acontece, é necessário realizar login novamente, pois algumas funcionalidades não funcionarão se o token não estiver atualizado.

Portanto, os objetivos desta issue são:

- [ ] Implementar a atualização de token
- [ ] Deslogar o usuário quando o token está expirado

**Comment by CleissonVieira** [comment]
O prazo do token de usuário foi atualizado para expirar a cada 2 meses.
Existe uma tarefa #119 para "deslogar" quando expirar (finalizar sessão)

Por esse motivo estou finalizando essa tarefa.
