### ISSUE TITLE
Criar estrutura da tela de mensagens

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#9]
A tela de mensagens é uma cópia exata do aplicativo Telegram: teremos chats em grupo e individuais. Além disso, determinados chats ficarão agrupados em uma “pasta”. Para essa primeira versão da tela de mensagem, basta replicar o layout de funcionamento do telegram/whatsapp sem que mensagens sejam realmente enviadas e recebidas (tudo pode ser fake).

Tela: [C001-A](https://docs.google.com/presentation/d/1cackIj-Hc1h3A9aYPCXs3neFbzRaNq2BO19AOxUAngY/edit#slide=id.g8e16bc710d_0_505)

![Descrição aplicativo - app-practice (5)](https://user-images.githubusercontent.com/512405/89335517-86879300-d66e-11ea-9e7c-ca50b5f5863a.png)

**Comment by andrewmsilva** [comment]
Independente de for fizer esta issue, recomendo utilizar isso: https://framework7.io/docs/messages.html

**Comment by Dovyski** [comment]
Quase chorei quando vi essa sugestão do @andrewmsilva. Com ele falou, vamos usar o https://framework7.io/docs/messages.html como base para criação do app.

**Comment by andrewmsilva** [comment]
Vou registrar aqui o meu progresso nesta issue. Foi feita uma visualização para as conversas em cards. Caso achem interessante, daria para agrupá-las em diferentes cards. Por exemplo, um card teria todos as conversas individuais, outro card teria os grupos.

Além disso, todo sistema de conversação precisa de algumas funcionalidades essenciais, como a criação de novas conversas, novos grupos e pesquisa. Então essas opções foram colocadas em um botão flutuante para deixar um visual clean e moderno.

A função de criar uma nova conversa já tem um `sheet-modal` pra chamar de seu, onde o usuário poderia digitar o idUFFS da pessoa com quem deseja conversar. O campo já está com validação automática, porém simples. A criação de grupos vai ser mais complicada de fazer, visto que terá vários campos.

Abaixo há um GIF pra visualizar o que foi feito até agora:

![new-chat](https://user-images.githubusercontent.com/18292676/90065465-b532e880-dcc2-11ea-9d96-1249c855e253.gif)

Além disso, também é necessário permitir remover conversas. O mais intuitivo seria apertar e segurar em cima da conversa e algumas opções aparecerem (como a de excluir). Por ora, fazer isso de um jeito simples ainda é um mistério pra mim, então continuarei trabalhando nos componentes das ações que estão no botão flutuante. 

Vale ressaltar que nenhuma funcionalidade foi implementada, só estou deixando os componentes e o fluxo de cada ação pré-prontos para agilizamos trabalho futuro.

Gostaria da opinião geral sobre o andamento e sobre a ideia de agrupar as conversas por cards.
