### ISSUE TITLE
Preparação para deploy no Google Play

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/app-practice#91]
Para que o app seja colocado no ar (mesmo que em debug), o projeto precisa ser ajustado em alguns aspectos. Essa issue é voltada a todos esses ajustes (inclusive de documentação para que qualquer pessoa saiba fazer o build).

**Comment by andrewmsilva** [comment]
Estou fazendo alguns ajustes de dependências.

**Comment by CleissonVieira** [comment]
Issue sem objetivo claro. Sobre a documentação do build eu criei a issue #116  , caso necessário da para acrescentar informação nela.
Sobre o que falta preparar para fazer o deploy é melhor ser conversado/dentificado e já criado issues para solução de situações específicas
